name: Docker Build and Push

on:
  workflow_dispatch:  # 仅允许手动触发
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: true
        default: 'latest'
      publish_latest:
        description: '同时发布为latest标签'
        required: true
        type: boolean
        default: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/ytbot
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置QEMU以支持多架构构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 设置Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录到DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 准备标签
      - name: Prepare Tags
        id: prep
        run: |
          VERSION=${{ github.event.inputs.version }}
          TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"
          
          # 如果选择同时发布为latest标签
          if [[ "${{ github.event.inputs.publish_latest }}" == "true" ]]; then
            TAGS="${TAGS},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          fi
          
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "将构建以下标签: ${TAGS}"

      # 构建并推送Docker镜像
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 