name: Build and Push Docker Images

# 修改触发条件为手动触发
on:
  workflow_dispatch:  # 添加手动触发
    inputs:
      version:
        description: '版本标签 (例如: v1.0.0)'
        required: true
        default: 'latest'
      platform:
        description: '构建平台'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64
      push_latest:
        description: '是否同时更新 latest 标签'
        required: true
        type: boolean
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        if: github.event.inputs.platform == 'arm64'
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Generate tags
        id: tags
        run: |
          # 只生成带架构后缀的标签
          TAGS="ainxxy/ytbot:${{ github.event.inputs.version }}-${{ github.event.inputs.platform }}"
          
          if [ "${{ github.event.inputs.push_latest }}" = "true" ]; then
            TAGS="$TAGS,ainxxy/ytbot:latest-${{ github.event.inputs.platform }}"
          fi
          
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ github.event.inputs.platform }}
          push: true
          tags: ${{ steps.tags.outputs.tags }} 